### ISSUE TITLE
Error Parsing HealthCheck Dataset when monitoring multiple PASOE instances?

### ISSUE THREAD

**Issue by c3rberus** [progress/iceberg#25] opened 2023-08-19 18:08 UTC
Looking at deploying the "monitoring" side of iceberg in production. The collector and monitoring application is deployed on the same machine (OE 12.2.12, AIX).

I can successfully deploy the Monitoring/Collector PASOE instance/database, and the Monitoring/Application code without issues, enabling metrics (pulse). Using default ports, I can get to the web UI and see monitoring data.

The moment I go to deploy Monitoring/Application to a 2nd PASOE instance (server has multiple PASOE instances), I get errors and there are no metrics being reported in the UI for the 2nd instance.

`
[2023-08-19T10:39:27.235-07:00] B.Intake | INFO - Health data received from production @ http://127.0.0.1:15605
[2023-08-19T10:39:27.236-07:00] B.Intake | ERROR - Error Parsing HealthCheck Dataset for production @ http://127.0.0.1:15605: Error parsing JSON: expected brace, but found bracket. (15358)
[2023-08-19T10:39:27.238-07:00] B.Intake | ERROR - Error Processing Health Data: Unable to read HealthCheck JSON into dataset for further processing.
`

The monitored PASOE instances are configured with identical settings other than the name/ports.

If I wipe everything and start over, this time deploying Monitoring/Application to the instance that was reporting errors processing health data FIRST - it works without any issues. Adding the 2nd instance (that previously worked when deployed to first), starts to experience the same errors.

Seems like the moment we go to add a 2nd instance to be monitored, the 2nd instance reports errors and no metrics are generated.

When enabling TRACE logging, and reviewing the monitor/temp folder, there is a bunch of .json files that get generated that have references to the FIRST instance that monitoring is deployed on, but no reference to the SECOND instance that has errors.

Any idea what we could do to debug this?

I suppose one could create multiple collector/monitor instances to potentially work around this, but it seems like the solution was built to support pulling in metrics from multiple PASOE instances.

**Comment by DustinGrau-PSC** [comment] 2023-08-21 12:24
The server (monitor) should be able to accept data from multiple instances, even from the same server. The data should be sent from 2 distinct ports since that is how PAS instances are distinguished internally.

To debug this, we're going to need a COMPLETE rundown of every command you issued to set up the instances--this includes deploying the application code which supports the advanced monitoring, enabling the health metrics, starting the instances, and most importantly starting the monitoring on each instance. Create 2 documents, one for each of your PAS instances and collect the command run and any output--we need to see if there's any obvious key differences between the enablement processes for these by diff'ing the 2 files.

If the enablement processes are good, then we can move on to the collection side. In all cases there are logging.config options which can be altered--changing the logging-level attributed to the monitoring (collection or parsing) code to TRACE will generate much more detail including dumping of the JSON files being transferred. That's a last-resort as it's obviously going to be quite noisy unless we know exactly what to look for.

**Comment by DustinGrau-PSC** [comment] 2023-08-22 14:29
Thank you so much for all the legwork on this, I agree that all looks expected. And the screenshots may have tipped me off to the problem. When you switch between PAS instances which have been collected (as confirmed by the intake.log) you have different Agent PID's and sessions, and sometimes the UI can get confused as to which was the last one it viewed. Here's what I think happened: when you switched between the PAS instances, the UI wasn't able to default to any specific PID and so it can't retrieve the necessary data. Go back to the Overview tab and select one of the agents (or better, a specific agent-session) and see if the context loads correctly for the remaining tabs for that PAS instance.

**Comment by DustinGrau-PSC** [comment] 2023-08-22 19:09
Gotcha, and that's very helpful. That confirms that the UI gets confused when switching between instances, as it's either not able to recall the last PID that was selected or it has wiped out that info by switching the server instance. I've run into this before but never so clearly reproduced the conditions. The workaround for the moment would be to select a PID when you first change servers, and the tell-tale sign of that is seeing "Agent  -" before any of the graph titles--there should always be an "Agent ##### -" when a PID is in context.

**Comment by DustinGrau-PSC** [comment] 2023-08-23 21:03
Overall this solution is much more performant (and safer) for production use than anything implemented prior. The collection of data should not impede normal operation of the agent, though we have not tested this at scale with super-high-transaction environments. Yes, we've pushed server instances internally and we have customers using this in the field, but we don't actively monitor how they use it or what kind of experiences they have. Usually if there's a problem then it would come back to me here in this repo, though most issues reported have been minor.

Most of the internal data gets purged between pulses, so there's going to be a tradeoff between pushing out the data (to clear the constructs and free memory internally) and how frequently you push that data out (as pushing every 1-2 seconds can have a bad effect). The default time used for the pulse interval at the moment is a good compromise on those points. The other factor is what you collect--the calltrees will enable a portion of the profiler code and so there could be a timing impact from that as well as retaining a lot of data that may never be used. At the minimum, reporting on the sessions and requests will give good insight but not overwhelm the collection system.

**Comment by DustinGrau-PSC** [comment] 2023-08-25 11:44
If you look at the "pulse_on" scripts, the default settings are "OPTIONS=sessions,requests,calltrees,ablobjs" which sends quite a bit of information as this is assumed to be used in development primarily. For production use the recommended settings are "OPTIONS=sessions,requests" which will provide comprehensive session data, including tracking of requests which helps determine any spikes in response times. If necessary you can scale back to just "sessions" which is very much bare-bones and the absolute minimum.

https://github.com/progress/iceberg/blob/main/PAS/Monitoring/Application/deploy/oe122/bin/pulse_on.sh

**Comment by DustinGrau-PSC** [comment] 2023-08-30 19:43
If you care to try out some development code I've made some modifications to a new branch. The main change was a ui.zip file in the Monitor/Collector folder. You can either unzip that into your ROOT/static folder or just re-deploy the Monitor instance.

https://github.com/progress/iceberg/tree/Sept23

**Comment by c3rberus** [comment] 2023-09-01 02:54
Dustin,

I have some good news :) I pulled the development code and re-created my test case, it works now. I have not been able to reproduce the original issue where it was not refreshing Agent Activity when switching between PASOE instances.

**Closed as completed** 2023-09-05 12:31 UTC
